# Generated by Django 3.2.8 on 2021-12-14 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('level', models.CharField(blank=True, choices=[('', 'Выберите уровень курса'), ('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255, verbose_name='Уровень курса')),
                ('new_words', models.PositiveIntegerField(blank=True, default=0, verbose_name='Число новых слов')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='courses/icons/', verbose_name='Иконка курса')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Обложка курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': '   Курсы',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название урока')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='lessons/icons/', verbose_name='Иконка урока')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='lessons/covers/', verbose_name='Обложка урока')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Урок из курса')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': '  Уроки',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('exercise_type', models.CharField(blank=True, choices=[('', 'Выберите тип задания'), ('word_miss_type', 'Задание с пропуском'), ('translate_type', 'Задание с переводом')], default='word_miss_type', max_length=255, verbose_name='Тип задания')),
                ('text', models.TextField(max_length=500, verbose_name='Текст вопроса')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson', verbose_name='Задание из урока')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': ' Задания',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Текст ответа')),
                ('right', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.exercise', verbose_name='Вариант ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('pk',),
            },
        ),
    ]
