# Generated by Django 3.2.8 on 2021-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255, null=True, verbose_name='Уровень курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='new_words',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Число новых слов'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('word_miss_type', 'Задание с пропуском'), ('translate_type', 'Задание с переводом')], default='word_miss_type', max_length=255, null=True, verbose_name='Тип задания'),
        ),
    ]
