# Generated by Django 3.2.8 on 2021-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211008_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_covers/', verbose_name='Обложка курса'),
        ),
    ]
