# Generated by Django 3.2.8 on 2021-10-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211008_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255,
                 verbose_name='Заголовок задания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='exercises', to='courses.course', verbose_name='Задание из урока')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
