# Generated by Django 3.2.8 on 2021-10-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_exercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': '   Курсы'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Задание', 'verbose_name_plural': ' Задания'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': '  Уроки'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='lesson',
        ),
    ]
