# Generated by Django 3.2.8 on 2021-10-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211027_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('', 'Выберите уровень курса'), ('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255, verbose_name='Уровень курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='new_words',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Число новых слов'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('', 'Выберите тип задания'), ('word_miss_type', 'Задание с пропуском'), ('translate_type', 'Задание с переводом')], default='word_miss_type', max_length=255, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Урок из курса'),
        ),
    ]
