# Generated by Django 3.2.8 on 2021-10-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20211008_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson', verbose_name='Задание из урока'),
            preserve_default=False,
        ),
    ]
