# Generated by Django 3.2.8 on 2021-10-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_exercise_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='courses_covers/', verbose_name='Иконка курса'),
        ),
    ]
