# Generated by Django 3.2.8 on 2021-10-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211009_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='courses/icon/', verbose_name='Обложка курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Иконка курса'),
        ),
    ]
