# Generated by Django 3.2.8 on 2021-10-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211009_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок курса'),
            preserve_default=False,
        ),
    ]
