# Generated by Django 3.2.8 on 2021-10-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
