# Generated by Django 3.2.8 on 2021-10-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], max_length=255, verbose_name='Уровень курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='new_words',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число новых слов'),
        ),
    ]
