# Generated by Django 3.2.8 on 2021-10-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20211009_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('pk',), 'verbose_name': 'Курс', 'verbose_name_plural': '   Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('pk',), 'verbose_name': 'Урок', 'verbose_name_plural': '  Уроки'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.AddField(
            model_name='lesson',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/icons/', verbose_name='Иконка урока'),
        ),
    ]
