# Generated by Django 3.2.8 on 2021-10-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20211009_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='icons',
            new_name='icon',
        ),
    ]
