# Generated by Django 3.2.8 on 2021-10-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_icons_lesson_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/cover/', verbose_name='Обложка урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='courses/cover/', verbose_name='Обложка курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='courses/icon/', verbose_name='Иконка курса'),
        ),
    ]
