# Generated by Django 3.2.8 on 2021-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20211009_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Обложка курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='courses/icons/', verbose_name='Иконка курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/covers/', verbose_name='Обложка урока'),
        ),
    ]
