# Generated by Django 3.2.8 on 2021-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20211009_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('word_miss_type', 'Задание с пропуском'), ('translate_type', 'Задание с переводом'), ('audio_type', 'Задание аудио-типа')], default='word_miss_type', max_length=255, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255, verbose_name='Уровень курса'),
        ),
    ]
