# Generated by Django 3.2.8 on 2021-10-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20211009_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_text',
            field=models.CharField(default='', help_text='Используйте "___" для вопросов с пропуском.', max_length=400, verbose_name='Текст вопроса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='right_answer',
            field=models.CharField(default='', max_length=400, verbose_name='Правильный ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='right_answer_translation',
            field=models.CharField(default='', max_length=400, verbose_name='Перевод правильного ответа'),
            preserve_default=False,
        ),
    ]
