# Generated by Django 3.2.8 on 2021-10-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20211009_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('pk',), 'verbose_name': 'Задание', 'verbose_name_plural': ' Задания'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(blank=True, choices=[('word_miss_type', 'Задание с пропуском'), ('translate_type', 'Задание с переводом')], default='word_miss_type', max_length=255, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название задания'),
        ),
    ]
