# Generated by Django 3.2.8 on 2021-10-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20211009_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='right_answer_translation',
        ),
        migrations.AlterField(
            model_name='course',
            name='new_words',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Число новых слов'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, verbose_name='Текст ответ')),
                ('right', models.BooleanField(verbose_name='Верный ответ')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.exercise', verbose_name='Вариант ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('pk',),
            },
        ),
    ]
