# Generated by Django 3.2.8 on 2021-10-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20211013_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='text',
            field=models.CharField(default='', max_length=500, verbose_name='Текст вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='right',
            field=models.BooleanField(default=False, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=400, verbose_name='Текст ответа'),
        ),
    ]
