# Generated by Django 3.2.8 on 2021-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20211013_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст вопроса'),
        ),
    ]
