# Generated by Django 3.2.8 on 2021-10-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_course'),
        ('users', '0002_auto_20211026_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(related_name='users', to='courses.Course', verbose_name='Выполненные курсы'),
        ),
    ]
