# Generated by Django 3.2.8 on 2021-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_course'),
        ('users', '0003_profile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lessons',
            field=models.ManyToManyField(related_name='users', to='courses.Lesson', verbose_name='Выполненные уроки'),
        ),
    ]
