# Generated by Django 3.2.8 on 2021-10-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211027_1950'),
        ('users', '0006_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='courses.Course', verbose_name='Выполненные курсы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='users', to='courses.Lesson', verbose_name='Выполненные уроки'),
        ),
    ]
